Dataset Summary Report Using Python and Pandas
1. Introduction

This notebook demonstrates how to load and explore a student dataset using Python and Pandas. The analysis focuses on understanding the basic structure, characteristics, data types, and missing values present in the dataset.

The dataset contains information about students, including their ID, name, age, course, marks, attendance percentage, and city.

2. Import Pandas

In [21]:
import pandas as pd

3. Load the Dataset

In [22]:
df = pd.read_csv("Day7_Student_Dataset.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

4. Display the First Few Rows

The head() function displays the first five rows of the dataset.

In [23]:
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

5. Display the Last Few Rows

The tail() function displays the last five rows.

In [24]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

6. Display Random Samples

The sample() function can be used to view random records from the dataset.

In [25]:
df.sample(5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi

This helps us examine randomly selected student records instead of only viewing the beginning or end of the dataset.

7. Check Dataset Shape

The shape attribute returns the number of rows and columns.

In [26]:
print("Rows and Columns:", df.shape)

Rows and Columns: (25, 7)

Result

The dataset contains:

25 rows
7 columns

8. Check Column Names

In [27]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

Available Features

The dataset contains the following 7 features:

Student_ID
Name
Age
Course
Marks
Attendance_Percentage
City

9. Check Dataset Index

In [28]:
print("Dataset Index:")
print(df.index)

Dataset Index:
RangeIndex(start=0, stop=25, step=1)

The DataFrame uses a default integer index starting from 0.

10. Check Data Types

In [29]:
print(df.dtypes)

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

Data Types

Column                                  	Data Type

Student_ID                                	int64
Name	                                      object
Age	                                        int64
Course	                                    object
Marks                                     	float64
Attendance_Percentage                     	float64
City                                      	object


The numerical columns are stored as integer or floating-point values, while text-based columns are stored as object.

11. Dataset Information Using info()

The info() function provides important information about the DataFrame, including the number of entries, columns, data types, and non-null values.

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

Observation

The dataset contains 25 entries and 7 columns.

The dataset has:

Integer columns: Student_ID, Age
Floating-point columns: Marks, Attendance_Percentage
Object/text columns: Name, Course, City

12. Descriptive Statistics

The describe() function provides statistical information about numerical columns.

In [31]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

It provides values such as:

Count
Mean
Standard deviation
Minimum
25th percentile
Median
75th percentile
Maximum

13. Check Missing Values

In [32]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

Missing Values Found

The dataset contains missing values in:

Marks → 1 missing value
Attendance_Percentage → 1 missing value
City → 1 missing value

The remaining columns do not contain missing values.

14. Calculate Total Missing Values

In [33]:
total_missing = df.isnull().sum().sum()

print("Total Missing Values:", total_missing)

Total Missing Values: 3

15. Check Unique Values

In [34]:
for column in df.columns:
    print(f"\n{column}:")
    print(df[column].unique())

Student_ID:
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025]

Name:
['Aarav Sharma' 'Zoya Khan' 'Rohan Mehta' 'Ananya Singh' 'Kabir Ali'
 'Ishita Gupta' 'Aditya Verma' 'Sara Ahmed' 'Arjun Nair' 'Mehak Bhat'
 'Vivaan Kapoor' 'Aisha Mir' 'Rahul Das' 'Sana Malik' 'Karan Joshi'
 'Hiba Sheikh' 'Dev Patel' 'Manya Rao' 'Yusuf Dar' 'Priya Menon'
 'Aman Kumar' 'Alina Shah' 'Nikhil Sood' 'Maryam Khan' 'Reyansh Jain']

Age:
[19 20 18 21 22 23]

Course:
['Data Science' 'AI' 'Computer Science']

Marks:
[87. 92. 76. 81. 69. 88. 95. 73. 84. 79. 91. 68. 72. 89. 77. 94. 86. 70.
 nan 90. 74. 96. 78. 85. 80.]

Attendance_Percentage:
[91. 95. 82. 88. 76. 93. 97. nan 86. 90. 94. 72. 81. 92. 85. 96. 89. 74.
 87. 78. 98. 83. 84.]

City:
['Srinagar' 'Delhi' 'Mumbai' 'Lucknow' 'Bengaluru' 'Pune' 'Hyderabad'
 'Kochi' 'Jaipur' 'Kolkata' nan 'Chandigarh' 'Ahmedabad' 'Chennai']

16. Basic Dataset Summary

In [35]:
print("===== DATASET SUMMARY =====")
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nFeatures:")
for column in df.columns:
  print("-", column)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

===== DATASET SUMMARY =====
Number of Rows: 25
Number of Columns: 7

Features:
- Student_ID
- Name
- Age
- Course
- Marks
- Attendance_Percentage
- City

Data Types:
Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

Missing Values:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

17. Final Observations

Based on the analysis, the following observations can be made:

The dataset contains 25 student records.
There are 7 columns/features.
Student_ID and Age are integer data types.
Marks and Attendance_Percentage are floating-point numerical columns.
Name, Course, and City are text-based columns.
There are 3 missing values in the dataset.
One value is missing from Marks.
One value is missing from Attendance_Percentage.
One value is missing from City.
The dataset can be further analyzed to study student performance, attendance, courses, and city-wise information.

18. Conclusion

This notebook demonstrated the basic exploration of a dataset using Pandas. Functions such as head(), tail(), sample(), shape, columns, index, dtypes, info(), describe(), and isnull() were used to understand the structure and characteristics of the student dataset.

Pandas makes it easy to inspect, summarize, and prepare datasets for further data analysis and visualization.